server:
  port: 8763
spring:
  application:
    name: springcloud-fang
  data:
    mongodb:
       uri: mongodb://fang:fanggby123@172.17.0.1:27017/fang
logging:
  path: /disk1/website/logs/fang/
  level:
    root: INFO 
    com:
      mie: DEBUG   
    org:
      apache: INFO  
      springframework:
        data:
          mongodb:
            core: DEBUG
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://clouddemo:8761/eureka/
feign:
  hystrix:
    enabled: true